---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: concept-drift
  namespace: default
  selfLink: "/apis/extensions/v1beta1/namespaces/default/deployments/concept-drift"
  labels:
    app: concept-drift
spec:
  replicas: 1
  selector:
    matchLabels:
      app: concept-drift
  template:
    metadata:
      creationTimestamp: 
      labels:
        app: concept-drift
    spec:
      containers:
      - name: concept-drift
        image: {{.Values.concept_drift_image}}
        resources: {}
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
