apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-07-09T06:19:14Z"
  generation: 1
  labels:
    app: catsdogs-serve
  name: catsdogs-serve
  namespace: default
  resourceVersion: "215106"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/catsdogs-serve
  uid: bccb9600-dfcb-4815-b8e9-ef04e6ee91ec
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: catsdogs-serve
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: catsdogs-serve
    spec:
      containers:
      - image: chaowen/catsdogs-tf-serve
        imagePullPolicy: Always
        name: catsdogs-tf-serve
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
